/***********************************************************************/
/*                                                                     */
/*  FILE        :main.cpp                                              */
/*  DATE        :Fri, May 18, 2012                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX63N                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  


//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif


#include "m2gr.h"

DigitalOut LED(p0) ;
DigitalIn  SW(p1) ;

void main(void)
{
	printf("Starting,...\n") ;
	while(1) {
		if(SW) {
			LED = 0x01 ;
		}	 else 	{
			LED = 0x00 ;
		}
	}

}


#ifdef __cplusplus
void abort(void)
{

}
#endif
